version: '3.1'
services:
  stats-server:
    build: ./stats
    image: stats_image
    container_name: explore_stats_server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - STATS_SERVER_PORT=9090
      - DB_HOST=explore_stats_db
      - DB_PORT=5432
      - DB_NAME=explore_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: explore_stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./emw
    image: emw_image
    container_name: explore_emw_server
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - EMW_SERVER_PORT=8080
      - EXPLORE_STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: explore_emw_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore_emw
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root