CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    name  VARCHAR(250) NOT NULL,

    CONSTRAINT users_unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,

    CONSTRAINT categories_unique_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(50) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE,

    CONSTRAINT compilations_unique_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              VARCHAR(120) NOT NULL,
    description        VARCHAR(7000),
    annotation         VARCHAR(2000),
    created            TIMESTAMP    NOT NULL,
    published          TIMESTAMP,
    event_date         TIMESTAMP    NOT NULL,
    category_id        BIGINT       NOT NULL,
    initiator_id       BIGINT       NOT NULL,
    lat                FLOAT        NOT NULL,
    lon                FLOAT        NOT NULL,
    state              VARCHAR(50)  NOT NULL,
    paid               BOOLEAN DEFAULT false,
    request_moderation BOOLEAN DEFAULT true,
    participant_limit  BIGINT  DEFAULT 0,

    CONSTRAINT events_fk_categories FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT events_fk_users FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP NOT NULL,
    event_id     BIGINT    NOT NULL,
    requester_id BIGINT    NOT NULL,
    status       VARCHAR(50) DEFAULT 'PENDING',

    CONSTRAINT requests_fk_events FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT requests_fk_users FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,

    CONSTRAINT compilations_events_comp_pk PRIMARY KEY (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS reactions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    positive BOOLEAN,
    timestamp TIMESTAMP NOT NULL,

    CONSTRAINT fk_reactions_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_reactions_events FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT reactions_unique_user_event UNIQUE (user_id, event_id)
);
